//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_setting
    {
        public int id { get; set; }
        public string sett_Deleted { get; set; }
        public Nullable<int> sett_CreatedBy { get; set; }
        public Nullable<System.DateTime> sett_CreatedDate { get; set; }
        public Nullable<int> sett_UpdatedBy { get; set; }
        public Nullable<System.DateTime> sett_UpdatedDate { get; set; }
        public Nullable<int> sett_WorkflowID { get; set; }
        public Nullable<int> sett_WorkflowItemID { get; set; }
        public Nullable<int> sett_ZoneID { get; set; }
        public Nullable<decimal> sett_Tax { get; set; }
        public string sett_isTax { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<decimal> sett_ExRate { get; set; }
        public Nullable<int> warehouseID { get; set; }
        public string sett_CustomerlastPrice { get; set; }
        public string sett_useSalesman { get; set; }
    }
}
