//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public int id { get; set; }
        public string user_Deleted { get; set; }
        public Nullable<int> user_CreatedBy { get; set; }
        public Nullable<System.DateTime> user_CreatedDate { get; set; }
        public Nullable<int> user_UpdatedBy { get; set; }
        public Nullable<System.DateTime> user_UpdatedDate { get; set; }
        public Nullable<int> user_ZoneID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string user_SID { get; set; }
        public string gender { get; set; }
        public string token { get; set; }
        public Nullable<int> user_SalesmanID { get; set; }
    }
}
