//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cust_CreatedBy { get; set; }
        public Nullable<System.DateTime> cust_CreatedDate { get; set; }
        public Nullable<int> cust_UpdatedBy { get; set; }
        public Nullable<System.DateTime> cust_UpdatedDate { get; set; }
        public Nullable<int> cust_ZoneID { get; set; }
        public Nullable<int> cust_WorkflowID { get; set; }
        public Nullable<int> cust_WorkflowItemID { get; set; }
        public string cust_Deleted { get; set; }
        public string phone { get; set; }
        public string cust_Email { get; set; }
        public string cust_Type { get; set; }
        public Nullable<int> cust_Parent { get; set; }
        public string code { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> cust_LastTransDate { get; set; }
        public Nullable<int> cust_NOI { get; set; }
        public string cust_Phone2 { get; set; }
        public Nullable<int> cust_PriceListID { get; set; }
        public string cust_Zone { get; set; }
    }
}
