//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int id { get; set; }
        public string item_Deleted { get; set; }
        public Nullable<int> item_CreatedBy { get; set; }
        public Nullable<System.DateTime> item_CreatedDate { get; set; }
        public Nullable<int> item_UpdatedBy { get; set; }
        public Nullable<System.DateTime> item_UpdatedDate { get; set; }
        public Nullable<int> item_ZoneID { get; set; }
        public Nullable<int> item_WorkflowID { get; set; }
        public Nullable<int> item_WorkflowItemID { get; set; }
        public string name { get; set; }
        public Nullable<int> itemGroupID { get; set; }
        public Nullable<decimal> price { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string item_isStock { get; set; }
        public string item_isSet { get; set; }
        public Nullable<decimal> item_SOAllocation { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> lastCost { get; set; }
        public Nullable<decimal> item_ReOrderPoint { get; set; }
        public Nullable<int> item_ItemLayout3 { get; set; }
        public string item_Size { get; set; }
        public string item_Weight { get; set; }
        public string item_Volume { get; set; }
        public string item_IsCommission { get; set; }
        public string item_Unit { get; set; }
    }
}
