//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemWarehouse
    {
        public int id { get; set; }
        public string itwh_Deleted { get; set; }
        public Nullable<int> itwh_CreatedBy { get; set; }
        public Nullable<System.DateTime> itwh_CreatedDate { get; set; }
        public Nullable<int> itwh_UpdatedBy { get; set; }
        public Nullable<System.DateTime> itwh_UpdatedDate { get; set; }
        public Nullable<int> itwh_WorkflowID { get; set; }
        public Nullable<int> itwh_WorkflowItemID { get; set; }
        public Nullable<int> itwh_ZoneID { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<int> wareHouseID { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> itwh_SOAllocation { get; set; }
        public Nullable<int> itwh_ItemLayout1 { get; set; }
    }
}
