//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemGroup
    {
        public int id { get; set; }
        public string itmg_Deleted { get; set; }
        public Nullable<int> itmg_CreatedBy { get; set; }
        public Nullable<System.DateTime> itmg_CreatedDate { get; set; }
        public Nullable<int> itmg_UpdatedBy { get; set; }
        public Nullable<System.DateTime> itmg_UpdatedDate { get; set; }
        public Nullable<int> itmg_ZoneID { get; set; }
        public Nullable<int> itmg_WorkflowID { get; set; }
        public Nullable<int> itmg_WorkflowItemID { get; set; }
        public string name { get; set; }
        public Nullable<int> itmg_ItemCatID { get; set; }
    }
}
