//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleOrderItem
    {
        public int id { get; set; }
        public string soit_Deleted { get; set; }
        public Nullable<int> soit_CreatedBy { get; set; }
        public Nullable<System.DateTime> soit_CreatedDate { get; set; }
        public Nullable<int> soit_UpdatedBy { get; set; }
        public Nullable<System.DateTime> soit_UpdatedDate { get; set; }
        public Nullable<int> soit_WorkflowID { get; set; }
        public Nullable<int> soit_WorkflowItemID { get; set; }
        public Nullable<int> soit_ZoneID { get; set; }
        public Nullable<int> soit_ItemID { get; set; }
        public string soit_Description { get; set; }
        public Nullable<int> soit_Qty { get; set; }
        public Nullable<decimal> soit_Price { get; set; }
        public Nullable<decimal> soit_Total { get; set; }
        public Nullable<int> saleOrderID { get; set; }
        public Nullable<decimal> soit_ShipQty { get; set; }
        public Nullable<decimal> soit_RemainQty { get; set; }
        public Nullable<int> soit_WarehouseID { get; set; }
        public string soit_Unit { get; set; }
    }
}
