//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarehouse
    {
        public int id { get; set; }
        public string ware_Deleted { get; set; }
        public Nullable<int> ware_CreatedBy { get; set; }
        public Nullable<System.DateTime> ware_CreatedDate { get; set; }
        public Nullable<int> ware_UpdatedBy { get; set; }
        public Nullable<System.DateTime> ware_UpdatedDate { get; set; }
        public Nullable<int> ware_WorkflowID { get; set; }
        public Nullable<int> ware_WorkflowItemID { get; set; }
        public Nullable<int> ware_ZoneID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    }
}
