//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THEntities : DbContext
    {
        public THEntities()
            : base("name=THEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblItemGroup> tblItemGroups { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<tblItemWarehouse> tblItemWarehouses { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<sys_setting> sys_setting { get; set; }
        public virtual DbSet<sm_doc> sm_doc { get; set; }
        public virtual DbSet<tblSaleOrder> tblSaleOrders { get; set; }
        public virtual DbSet<tblSaleOrderItem> tblSaleOrderItems { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblInvoiceItem> tblInvoiceItems { get; set; }
        public virtual DbSet<vInvoice> vInvoices { get; set; }
    }
}
